sudo: required
services:
  - docker

jobs:
  include:
    - name: indigo
      script: docker run --rm -it -v $(pwd):/catkin_ws/src/natnet_ros -w /catkin_ws ros:indigo-perception src/natnet_ros/ci.sh
    - name: kinetic
      script: docker run --rm -it -v $(pwd):/catkin_ws/src/natnet_ros -w /catkin_ws ros:kinetic-perception src/natnet_ros/ci.sh
    - name: melodic
      script: docker run --rm -it -v $(pwd):/catkin_ws/src/natnet_ros -w /catkin_ws ros:melodic-perception src/natnet_ros/ci.sh
